# Generated by OmopViewer 0.0.0.900
# Be careful editing this file

library(OmopViewer)
library(bslib)
library(here)
library(shiny)

data <- OmopViewer::importSummarisedResult(here::here("data")) |>
  OmopViewer::correctSettings()
