# Generated by omopViewer 0.0.0.900
# Be careful editing this file

library(bslib)
library(shiny)
library(omopViewer)
library(here)

data <- omopViewer::importSummarisedResult(here::here("data")) |>
  omopViewer::correctSettings()
