# Generated by OmopViewer 0.0.0.900
# Be careful editing this file

server <- function(input, output, session) {
  # download raw data -----
  output$download_raw <- shiny::downloadHandler(
    filename = "results.csv",
    content = function(file) {
      OmopViewer::exportSummarisedResult(data, fileName = file)
    }
  )
}
