
#' Export and launch a static shiny specific to the provided results.
#'
#' @param result A summarised_result object.
#' @param directory Directory to create the shiny.
#' @param logo Name of a logo or path to a logo. If NULL no logo is included.
#' Only svg format allowed for the moment.
#' @param title title of the shiny
#' @param open Whether to open the shiny app project.
#'
#' @return The shiny app will be created in directory.
#' @export
#'
exportStaticApp <- function(result = emptySummarisedResult(),
                            logo = "HDS",
                            title = "My study",
                            directory = getwd(),
                            open = rlang::is_interactive()) {
  # input check
  result <- omopgenerics::validateResultArgument(result)
  omopgenerics::assertCharacter(directory, length = 1)
  omopgenerics::assertLogical(open, length = 1)
  omopgenerics::assertCharacter(logo, length = 1, null = TRUE)
  omopgenerics::assertCharacter(title, length = 1)

  # create directory if it does not exit
  if (!dir.exists(directory)) {
    cli::cli_inform(c("i" = "Provided directory does not exist, it will be created."))
    dir.create(path = directory, recursive = TRUE)
    cli::cli_inform(c("v" = "directory created: {.pkg {directory}}"))
  }

  # processing data
  cli::cli_inform(c("i" = "Processing data"))
  resType <- omopgenerics::settings(result)[["result_type"]] |> unique()
  mes <- "Data processed: {length(resType)} result type{?s} idenfied"
  if (length(resType) == 0) {
    resType <- character()
    mes <- c("!" = paste0(mes, "."))
  } else {
    mes <- c("v" = paste0(mes, ": {.var {resType}}."))
  }
  cli::cli_inform(mes)
  if (length(resType) == 0) {
    cli::cli_inform(c("!" = "No result_type(s) found, the generated shiny will be empty."))
  }

  choices <- getChoices(result)

  # create shiny
  directory <- paste0(directory, "/shiny")
  dir.create(path = directory, showWarnings = FALSE)
  cli::cli_inform(c("i" = "Creating shiny from provided data"))
  logo <- copyLogos(logo, directory)
  ui <- c(messageShiny(), uiStatic(choices = choices, logo = logo, title = title))
  server <- c(messageShiny(), serverStatic(resultTypes = names(choices)))
  global <- c(messageShiny(), omopViewerGlobal)
  dir.create(paste0(directory, "/data"), showWarnings = FALSE)
  writeLines(ui, con = paste0(directory, "/ui.R"))
  writeLines(server, con = paste0(directory, "/server.R"))
  writeLines(global, con = paste0(directory, "/global.R"))
  writeLines(omopViewerProj, con = paste0(directory, "/shiny.Rproj"))
  omopgenerics::exportSummarisedResult(
    result,
    minCellCount = 0,
    fileName = "results.csv",
    path = paste0(directory, "/data"))
  cli::cli_inform(c("v" = "Shiny created in: {.pkg {directory}}"))

  # open shiny
  if (open) {
    cli::cli_inform(c("i" = "Launching shiny"))
    usethis::proj_activate(directory)
  }

  return(invisible())
}

messageShiny <- function() {
  c(
    paste0(
      "# Generated by omopViewer ",
      as.character(utils::packageVersion("omopViewer"))
    ),
    "# Be careful editing this file",
    ""
  )
}
copyLogos <- function(logo, directory) {
  # Create 'www' directory if it doesn't exist
  dir.create(paste0(directory, "/www"), showWarnings = FALSE)
  hdsLogo <- system.file("/www/images/hds_logo.svg", package = "omopViewer")
  ohdsiLogo <- system.file("/www/images/ohdsi_logo.svg", package = "omopViewer")
  if (is.null(logo)) {
    return(NULL)
  }
  if (logo == "HDS") {
    to <- paste0(directory, "/www/hds_logo.svg")
    file.copy(from = hdsLogo, to = to, overwrite = TRUE)
    return("hds_logo.svg")
  } else if (logo == "OHDSI") {
    to <- paste0(directory, "/www/ohdsi_logo.svg")
    file.copy(from = ohdsiLogo, to = to, overwrite = TRUE)
    return("ohdsi_logo.svg")
  } else if (file.exists(logo)) {
    nm <- basename(logo)
    to <- paste0(directory, "/www/", nm)
    file.copy(from = logo, to = to, overwrite = TRUE)
    return(nm)
  } else {
    cli::cli_warn(c("!" = "Logo couldn't be found."))
    return(NULL)
  }
  return(NULL)
}


# ui ----
uiStatic <- function(choices = list(),
                     logo = NULL,
                     title = "My study",
                     background = TRUE) {
  # initial checks
  omopgenerics::assertList(choices, named = TRUE)
  omopgenerics::assertCharacter(logo, length = 1, null = TRUE)
  omopgenerics::assertCharacter(title, length = 1)
  omopgenerics::assertLogical(background, length = 1)

  c(
    'ui <- bslib::page_navbar(',
    c(
      pageTitle(title, logo),
      createBackground(background, title, logo),
      createUi(names(choices), choices),
      'bslib::nav_spacer()',
      createAbout("hds_logo.svg"),
      'bslib::nav_item(bslib::input_dark_mode(id ="dark_mode", mode = "light"))'
    ) |>
      paste0(collapse = ",\n"),
    ')'
  ) |>
    paste0(collapse = "\n") |>
    styleCode()
}
pageTitle <- function(title, logo) {
  if (is.null(logo)) {
    x <- 'title = "{title}"'
  } else {
    x <- 'title = shiny::tags$span(
      shiny::tags$img(
        src = "{logo}",
        width = "auto",
        height = "46px",
        class = "me-3",
        alt = "logo"
      ),
      "{title}"
    )'
  }
  x <- glue::glue(x) |> as.character()
  return(x)
}

# server ----
serverStatic <- function(resultTypes = character()) {
  # initial checks
  omopgenerics::assertCharacter(resultTypes, unique = TRUE)

  paste0(
    c(
      "server <- function(input, output, session) {",
      createServer(resultTypes, data = "data"),
      "}"
    ),
    collapse = "\n"
  ) |>
    styleCode()
}

# utilities ----
formatTit <- function(x) {
  x |>
    stringr::str_replace_all(pattern = "_", replacement = " ") |>
    stringr::str_to_sentence()
}
formatCamel <- function(x) {
  x |>
    snakecase::to_any_case(case = "upper_camel", numerals = "asis")
}
formatSnake <- function(x) {
  x |>
    snakecase::to_any_case(case = "snake", numerals = "asis")
}
cast <- function(x) {
  if (is.character(x)) {
    if (length(x) == 0) {
      x <- "character()"
    } else {
      x <- paste0('c("', paste0(x, collapse = '", "'), '")')
    }
  } else if (is.null(x)) {
    x <- "NULL"
  } else if (is.call(x)) {
    x <- deparse(x)
  } else {
    x <- paste0('c(', paste0(x, collapse = ', '), ')')
  }
  return(x)
}
subs <- function(x, pat, subst) {
  id <- which(x == pat)
  if (length(id) == 1) {
    n <- length(x)
    if (id == 1) {
      x <- c(subst, x[-1])
    } else if (id == n) {
      x <- c(x[-n], subst)
    } else {
      x <- c(x[1:(id-1)], subst, x[(id+1):n])
    }
  }
  return(x)
}
emptySummarisedResult <- function() {
  omopgenerics::emptySummarisedResult(settings = dplyr::tibble(
    result_id = integer(),
    result_type = character(),
    package_name = character(),
    package_version = character()
  ))
}
