
#' Export and launch a static shiny specific to the provided results.
#'
#' @param result A summarised_result object.
#' @param directory Directory to create the shiny.
#' @param logo Name of a logo or path to a logo. If NULL no logo is included.
#' Only svg format allowed for the moment.
#' @param title title of the shiny
#' @param background Content to fill the background panel. If `NULL`, this panel
#' will not appear in the Shiny UI. This argument can be populated in two ways:
#' 1) A character string containing `bslib` code to go directly inside
#' `bslib::card()`.
#' 2) A named character vector where the names correspond to specific`bslib`
#' card elements: "header", "title", "subtitle", "body", and "footer". Each
#' element's name indicates the type of text it will fill. The order of these
#' elements is important when displaying the content. Markdown sythax for text
#' styling is supported.
#' @param summary Whether to include a panel with a summary of content in the
#' `result`.
#' @param panels List specifying order of results. Each panel is determined
#' by the available result types in the result object. Panels for any available
#' results not specified will be included after the specified result tabs.
#' @param open Whether to open the shiny app project.
#' @param theme Assign a theme to the shiny app using bslib::bs_theme()
#'
#' @return The shiny app will be created in directory.
#'
#' @export
#'
#' @examples {
#' tdir <- here::here()
#' exportStaticApp(result = omopgenerics::emptySummarisedResult(), directory = tdir, logo = NULL, theme = "bslib::bs_theme(bg = '#bb0a1e', fg = '#0000ff')")
#' }
#'
exportStaticApp <- function(result,
                            logo = "ohdsi",
                            title = "",
                            background = NULL,
                            summary = TRUE,
                            directory = getwd(),
                            panels = list(),
                            theme = NULL,
                            open = rlang::is_interactive()) {
  # input check
  result <- omopgenerics::validateResultArgument(result)
  background <- validateBackground(background)
  omopgenerics::assertCharacter(directory, length = 1)
  omopgenerics::assertLogical(open, length = 1)
  omopgenerics::assertCharacter(logo, length = 1, null = TRUE)
  omopgenerics::assertCharacter(title, length = 1)
  omopgenerics::assertLogical(summary, length = 1)
  omopgenerics::assertCharacter(theme, length = 1, null = TRUE)
  panels <- validatePanels(panels, getChoices(result))
  sum <- validateSummary(summary, result)
  directory <- validateDirectory(directory)
  if (isTRUE(directory)) {
    return(cli::cli_inform(c("i" = "{.strong shiny} folder will not be overwritten. Stopping process.")))
  }

  # processing data
  cli::cli_inform(c("i" = "Processing data"))
  resType <- omopgenerics::settings(result)[["result_type"]] |> unique()
  mes <- "Data processed: {length(resType)} result type{?s} idenfied"
  if (length(resType) == 0) {
    resType <- character()
    mes <- c("!" = paste0(mes, "."))
  } else {
    mes <- c("v" = paste0(mes, ": {.var {resType}}."))
  }
  cli::cli_inform(mes)
  if (length(resType) == 0) {
    cli::cli_inform(c("!" = "No result_type(s) found, the generated shiny will be empty."))
  }

  # create shiny
  directory <- file.path(directory, "shiny")
  dir.create(path = directory, showWarnings = FALSE)
  cli::cli_inform(c("i" = "Creating shiny from provided data"))
  logo <- copyLogos(logo, directory)
  ui <- c(messageShiny(), uiStatic(choices = panels$choices, logo = logo, title = title, summary = sum, background = background, theme = theme))
  server <- c(messageShiny(), serverStatic(resultTypes = panels$result_order))
  global <- c(messageShiny(), omopViewerGlobal)
  dir.create(paste0(directory, "/data"), showWarnings = FALSE)
  writeLines(ui, con = paste0(directory, "/ui.R"))
  writeLines(server, con = paste0(directory, "/server.R"))
  writeLines(global, con = paste0(directory, "/global.R"))
  writeLines(omopViewerProj, con = paste0(directory, "/shiny.Rproj"))
  omopgenerics::exportSummarisedResult(
    result,
    minCellCount = 0,
    fileName = "results.csv",
    path = paste0(directory, "/data")
  )
  cli::cli_inform(c("v" = "Shiny created in: {.pkg {directory}}"))

  # open shiny
  if (open) {
    cli::cli_inform(c("i" = "Launching shiny"))
    usethis::proj_activate(directory)
  }

  return(invisible())
}

messageShiny <- function() {
  c(
    paste0(
      "# Generated by omopViewer ",
      as.character(utils::packageVersion("omopViewer"))
    ),
    "# Be careful editing this file",
    ""
  )
}
copyLogos <- function(logo, directory) {
  # Create 'www' directory if it doesn't exist
  dir.create(paste0(directory, "/www"), showWarnings = FALSE)

  # HDS logo must be copied always as it is needed for about tab
  hdsLogo <- logoPath("hds")
  to <- paste0(directory, "/www/hds_logo.svg")
  file.copy(from = hdsLogo, to = to, overwrite = TRUE)

  if (is.null(logo)) {
    return(NULL)
  }

  # search for standard logo naming:
  logo <- logoPath(logo)

  # copy the logo if exists
  if (file.exists(logo)) {
    nm <- basename(logo)
    to <- paste0(directory, "/www/", nm)
    if (logo != hdsLogo) {
      file.copy(from = logo, to = to, overwrite = TRUE)
    }
    return(nm)
  } else {
    cli::cli_warn(c("!" = "Logo couldn't be found."))
    return(NULL)
  }
}

logoPath <- function(logo) {
  lowLogo <- stringr::str_to_lower(logo)
  # add more logoKeywords in data-raw/internalData
  if (lowLogo %in% logoKeywords) {
    system.file(paste0("/logos/", lowLogo, "_logo.svg"), package = "omopViewer")
  } else {
    logo
  }
}

# ui ----
uiStatic <- function(choices = list(),
                     logo = NULL,
                     title = "",
                     background = NULL,
                     summary = NULL,
                     theme = NULL) {
  # initial checks
  omopgenerics::assertList(choices, named = TRUE)
  omopgenerics::assertCharacter(logo, length = 1, null = TRUE)
  omopgenerics::assertCharacter(title, length = 1)

  # Create the bslib::bs_theme() call, or use NULL if not provided
  theme_setting <- if (!is.null(theme)) {
    paste0("theme = ", theme, ",")
  } else {
    ""
  }
  c(
    "ui <- bslib::page_navbar(",
    theme_setting,
    c(
      pageTitle(title, logo),
      createBackground(background = background, logo = logo),
      createSummary(summary, logo),
      createUi(choices),
      "bslib::nav_spacer()",
      createAbout("hds_logo.svg"),
      'bslib::nav_item(bslib::input_dark_mode(id ="dark_mode", mode = "light"))'
    ) |>
      paste0(collapse = ",\n"),
    ")"
  ) |>
    paste0(collapse = "\n") |>
    styleCode()
}

pageTitle <- function(title, logo) {
  if (is.null(logo)) {
    x <- 'title = "{title}"'
  } else {
    x <- 'title = shiny::tags$span(
      shiny::tags$img(
        src = "{logo}",
        width = "auto",
        height = "46px",
        class = "me-3",
        alt = "logo"
      ),
      "{title}"
    )'
  }
  x <- glue::glue(x) |> as.character()
  return(x)
}

# server ----
serverStatic <- function(resultTypes = character()) {
  # initial checks
  omopgenerics::assertCharacter(resultTypes, unique = TRUE, null = TRUE)

  paste0(
    c(
      "server <- function(input, output, session) {",
      createServer(resultTypes, data = "data"),
      "}"
    ),
    collapse = "\n"
  ) |>
    styleCode()
}

# utilities ----
formatTit <- function(x) {
  x |>
    stringr::str_replace_all(pattern = "_", replacement = " ") |>
    stringr::str_to_sentence()
}
formatCamel <- function(x) {
  x |>
    snakecase::to_any_case(case = "upper_camel", numerals = "asis")
}
formatSnake <- function(x) {
  x |>
    snakecase::to_any_case(case = "snake", numerals = "asis")
}
cast <- function(x) {
  if (is.character(x)) {
    if (length(x) == 0) {
      x <- "character()"
    } else {
      x <- paste0('c("', paste0(x, collapse = '", "'), '")')
    }
  } else if (is.null(x)) {
    x <- "NULL"
  } else if (is.call(x)) {
    x <- deparse(x)
  } else {
    x <- paste0("c(", paste0(x, collapse = ", "), ")")
  }
  return(x)
}
subs <- function(x, pat, subst) {
  id <- which(x == pat)
  if (length(id) == 1) {
    n <- length(x)
    if (id == 1) {
      x <- c(subst, x[-1])
    } else if (id == n) {
      x <- c(x[-n], subst)
    } else {
      x <- c(x[1:(id - 1)], subst, x[(id + 1):n])
    }
  }
  return(x)
}
emptySummarisedResult <- function() {
  omopgenerics::emptySummarisedResult(settings = dplyr::tibble(
    result_id = integer(),
    result_type = character(),
    package_name = character(),
    package_version = character()
  ))
}
