
#' Launch a dynamic shiny app wher you can upload results.
#'
#' @return Launches the shiny app.
#' @export
#'
launchDynamicApp <- function() {
  shiny::shinyApp(ui = uiDynamic(), server = serverDynamic)
}

#' Export and launch a static shiny specific to the provided results.
#'
#' @param result A summarised_result object.
#' @param directory Directory to create the shiny.
#' @param logo Name of a logo or path to a logo. If NULL no logo is included.
#' Only svg format allowed for the moment.
#' @param open Whether to open the shiny app project.
#'
#' @return The shiny app will be created in directory.
#' @export
#'
exportStaticApp <- function(result = emptySummarisedResult(),
                            logo = "HDS",
                            directory = getwd(),
                            open = rlang::is_interactive()) {
  # input check
  result <- omopgenerics::validateResultArguemnt(result)
  omopgenerics::assertCharacter(directory, length = 1)
  omopgenerics::assertLogical(open, length = 1)
  omopgenerics::assertCharacter(logo, length = 1, null = TRUE)

  # create directory if it does not exit
  if (!dir.exists(directory)) {
    cli::cli_inform(c("i" = "Provided directory does not exist, it will be created."))
    dir.create(path = directory, recursive = TRUE)
    cli::cli_inform(c("v" = "directory created: {.pkg {directory}}"))
  }

  # processing data
  cli::cli_inform(c("i" = "Processing data"))
  resType <- omopgenerics::settings(result)[["result_type"]] |> unique()
  mes <- "Data processed: {length(resType)} result type{?s} idenfied"
  if (length(resType) == 0) {
    resType <- character()
    mes <- c("!" = paste0(mes, "."))
  } else {
    mes <- c("v" = paste0(mes, ": {.var {resType}}."))
  }
  cli::cli_inform(mes)
  if (length(resType) == 0) {
    cli::cli_inform(c("!" = "No result_type(s) found, the generated shiny will be empty."))
  }

  # create shiny
  directory <- paste0(directory, "/shiny")
  dir.create(path = directory)
  cli::cli_inform(c("i" = "Creating shiny from provided data"))
  logo <- copyLogos(logo, directory)
  ui <- c(messageShiny(), uiStatic(result = result, asText = TRUE, logo = logo))
  server <- c(messageShiny(), serverStatic(result = result, asText = TRUE))
  global <- c(messageShiny(), omopViewerGlobal)
  dir.create(paste0(directory, "/data"))
  writeLines(ui, con = paste0(directory, "/ui.R"))
  writeLines(server, con = paste0(directory, "/server.R"))
  writeLines(global, con = paste0(directory, "/global.R"))
  writeLines(omopViewerProj, con = paste0(directory, "/shiny.Rproj"))
  omopgenerics::exportSummarisedResult(
    result,
    minCellCount = 0,
    fileName = "results.csv",
    path = paste0(directory, "/data"))
  cli::cli_inform(c("v" = "Shiny created in: {.pkg {directory}}"))

  # open shiny
  if (open) {
    cli::cli_inform(c("i" = "Launching shiny"))
    usethis::proj_activate(directory)
  }

  return(invisible())
}

messageShiny <- function() {
  c(
    paste0(
      "# Generated by omopViewer ",
      as.character(utils::packageVersion("omopViewer"))
    ),
    "# Be careful editing this file", ""
  )
}
copyLogos <- function(logo, directory) {
  dir.create(paste0(directory, "/www"))
  from <- system.file("/www/images/hds_logo.svg", package = "omopViewer")
  to <- paste0(directory, "/www/hds_logo.svg")
  file.copy(from = from, to = to, overwrite = TRUE)
  if (!is.null(logo)) {
    if (logo == "HDS") {
      return("hds_logo.svg")
    } else if (file.exists(logo)) {
      nm <- basename(logo)
      to <- paste0(directory, "/www/", nm)
      file.copy(from = logo, to = to, overwrite = TRUE)
      return(nm)
    } else {
      cli::cli_warn(c("!" = "Logo couldn't be found."))
      return(NULL)
    }
  }
  return(NULL)
}
