
#' Export and launch a static shiny specific to the provided results.
#'
#' @param result A summarised_result object.
#' @param directory Directory to create the shiny.
#' @param logo Name of a logo or path to a logo. If NULL no logo is included.
#' Only svg format allowed for the moment.
#' @param open Whether to open the shiny app project.
#'
#' @return The shiny app will be created in directory.
#' @export
#'
exportStaticApp <- function(result = emptySummarisedResult(),
                            logo = "HDS",
                            directory = getwd(),
                            open = rlang::is_interactive()) {
  # input check
  result <- omopgenerics::validateResultArguemnt(result)
  omopgenerics::assertCharacter(directory, length = 1)
  omopgenerics::assertLogical(open, length = 1)
  omopgenerics::assertCharacter(logo, length = 1, null = TRUE)

  # create directory if it does not exit
  if (!dir.exists(directory)) {
    cli::cli_inform(c("i" = "Provided directory does not exist, it will be created."))
    dir.create(path = directory, recursive = TRUE)
    cli::cli_inform(c("v" = "directory created: {.pkg {directory}}"))
  }

  # processing data
  cli::cli_inform(c("i" = "Processing data"))
  resType <- omopgenerics::settings(result)[["result_type"]] |> unique()
  mes <- "Data processed: {length(resType)} result type{?s} idenfied"
  if (length(resType) == 0) {
    resType <- character()
    mes <- c("!" = paste0(mes, "."))
  } else {
    mes <- c("v" = paste0(mes, ": {.var {resType}}."))
  }
  cli::cli_inform(mes)
  if (length(resType) == 0) {
    cli::cli_inform(c("!" = "No result_type(s) found, the generated shiny will be empty."))
  }

  # create shiny
  directory <- paste0(directory, "/shiny")
  dir.create(path = directory)
  cli::cli_inform(c("i" = "Creating shiny from provided data"))
  logo <- copyLogos(logo, directory)
  ui <- c(messageShiny(), uiStatic(result = result, logo = logo))
  server <- c(messageShiny(), serverStatic(result = result))
  global <- c(messageShiny(), omopViewerGlobal)
  dir.create(paste0(directory, "/data"))
  writeLines(ui, con = paste0(directory, "/ui.R"))
  writeLines(server, con = paste0(directory, "/server.R"))
  writeLines(global, con = paste0(directory, "/global.R"))
  writeLines(omopViewerProj, con = paste0(directory, "/shiny.Rproj"))
  omopgenerics::exportSummarisedResult(
    result,
    minCellCount = 0,
    fileName = "results.csv",
    path = paste0(directory, "/data"))
  cli::cli_inform(c("v" = "Shiny created in: {.pkg {directory}}"))

  # open shiny
  if (open) {
    cli::cli_inform(c("i" = "Launching shiny"))
    usethis::proj_activate(directory)
  }

  return(invisible())
}

# ui ----
messageShiny <- function() {
  c(
    paste0(
      "# Generated by omopViewer ",
      as.character(utils::packageVersion("omopViewer"))
    ),
    "# Be careful editing this file", ""
  )
}
copyLogos <- function(logo, directory) {
  dir.create(paste0(directory, "/www"))
  from <- system.file("/www/images/hds_logo.svg", package = "omopViewer")
  to <- paste0(directory, "/www/hds_logo.svg")
  file.copy(from = from, to = to, overwrite = TRUE)
  if (!is.null(logo)) {
    if (logo == "HDS") {
      return("hds_logo.svg")
    } else if (file.exists(logo)) {
      nm <- basename(logo)
      to <- paste0(directory, "/www/", nm)
      file.copy(from = logo, to = to, overwrite = TRUE)
      return(nm)
    } else {
      cli::cli_warn(c("!" = "Logo couldn't be found."))
      return(NULL)
    }
  }
  return(NULL)
}
uiStatic <- function(result = emptySummarisedResult(),
                     logo = NULL,
                     title = "My study",
                     background = TRUE) {
  # initial checks
  result <- omopgenerics::validateResultArguemnt(result)
  omopgenerics::assertCharacter(logo, length = 1, null = TRUE)
  omopgenerics::assertCharacter(title, length = 1)
  omopgenerics::assertLogical(background, length = 1)

  elements <- c(
    createTitle(title, logo),
    createBackground(background, title, logo),
    createPanels(result),
    'bslib::nav_spacer()',
    createAbout(),
    'bslib::nav_item(bslib::input_dark_mode(id ="dark_mode", mode = "light"))'
  ) |>
    paste0(collapse = ",\n")

  'ui <- bslib::page_navbar(
  {elements}
  )' |>
    glue::glue() |>
    as.character() |>
    styleCode()
}
createTitle <- function(title, logo) {
  if (is.null(logo)) {
    x <- 'title = "{title}"'
  } else {
    x <- 'title = shiny::tags$span(
      shiny::tags$img(
        src = "{logo}",
        width = "auto",
        height = "46px",
        class = "me-3",
        alt = "logo"
      ),
      "{title}"
    )'
  }
  x <- glue::glue(x) |> as.character()
  return(x)
}
createPanels <- function(result) {
  choices <- getChoices(result)
  tabs <- names(choices)
  panel <- character()
  for (tab in tabs) {
    title <- getPanelTitle(tab)
    icon <- getPanelIcon(tab)
    sidebar <- getPanelSidebar(tab, choices[[tab]])
    content <- c(title, icon, sidebar) |>
      paste0(collapse = ",\n")
    panel <- c(
      panel,
      'bslib::nav_panel(
        {content}
      )' |>
        glue::glue() |>
        as.character()
    )
  }
  panel <- paste0(panel, collapse = ",\n")
  return(panel)
}
getInfo <- function(rt, info, def) {
  x <- omopViewerTabs[[info]][omopViewerTabs$result_type == rt]
  if (length(x) == 1 && !is.na(x)) return(x)
  def
}
getPanelTitle <- function(tab) {
  paste0('title = "', getInfo(tab, "title", formatTit(tab)), '"')
}
getPanelIcon <- function(tab) {
  icon <- getInfo(tab, "icon", NA_character_)
  if (is.na(icon)) return(NULL)
  paste0('icon = shiny::icon("', icon, '")')
}

# server ----
serverStatic <- function(result = emptySummarisedResult()) {
  # initial checks
  result <- omopgenerics::validateResultArguemnt(result)

  resultType <- omopgenerics::settings(result) |>
    dplyr::select("result_type") |>
    dplyr::distinct() |>
    dplyr::pull()

  serv <- purrr::map_chr(resultType, \(x) {
    c(glue::glue("# {x} -----"),
      glue::glue("## raw {x} -----"),
      getRawRt(x),
      glue::glue("## tidy {x} -----"),
      getTidyRt(x),
      glue::glue("## formatted {x} -----"),
      getFormattedRt(x),
      glue::glue("## plot {x} -----"),
      getPlotRt(x),
      "\n"
    ) |>
      paste0(collapse = "\n")
  }) |>
    paste0(collapse = "\n")

  serv <- paste0(
    c("server <- function(input, output, session) {", serv, "}"),
    collapse = "\n"
  ) |>
    styleCode()

  return(serv)
}

# utilities ----
formatTit <- function(x) {
  x |>
    stringr::str_replace_all(pattern = "_", replacement = " ") |>
    stringr::str_to_sentence()
}
formatCamel <- function(x) {
  x |>
    snakecase::to_any_case(case = "upper_camel", numerals = "asis")
}
formatSnake <- function(x) {
  x |>
    snakecase::to_any_case(case = "snake", numerals = "asis")
}
cast <- function(x) {
  if (is.character(x)) {
    if (length(x) == 0) {
      x <- "character()"
    } else {
      x <- paste0('c("', paste0(x, collapse = '", "'), '")')
    }
  } else if (is.null(x)) {
    x <- "NULL"
  } else if (is.call(x)) {
    x <- deparse(x)
  } else {
    x <- paste0('c(', paste0(x, collapse = ', '), ')')
  }
  return(x)
}
subs <- function(x, pat, subst) {
  id <- which(x == pat)
  if (length(id) == 1) {
    n <- length(x)
    if (id == 1) {
      x <- c(subst, x[-1])
    } else if (id == n) {
      x <- c(x[-n], subst)
    } else {
      x <- c(x[1:(id-1)], subst, x[(id+1):n])
    }
  }
  return(x)
}
emptySummarisedResult <- function() {
  omopgenerics::emptySummarisedResult(settings = dplyr::tibble(
    result_id = integer(),
    result_type = character(),
    package_name = character(),
    package_version = character()
  ))
}
