# DO NOT EDIT THIS FILE
# IT IS USED IN THE GITHUB ACTION

devtools::load_all()
exportStaticApp(
  result = omopViewerResults,
  directory = file.path(getwd(), "extras"),
  background = file.path(getwd(), "extras", "backgroundExample.md")
)
renv::init()
rsconnect::setAccountInfo(
  name = "dpa-pde-oxford",
  token = Sys.getenv("SHINYAPPS_TOKEN"),
  secret = Sys.getenv("SHINYAPPS_SECRET")
)
rsconnect::deployApp(
  appDir = file.path(getwd(), "extras", "shiny"),
  appName = appName,
  forceUpdate = TRUE
)
