# DO NOT EDIT THIS FILE
# IT IS USED IN THE GITHUB ACTION

rsconnect::setAccountInfo(
  name = "dpa-pde-oxford",
  token = Sys.getenv("SHINYAPPS_TOKEN"),
  secret = Sys.getenv("SHINYAPPS_SECRET")
)
rsconnect::deployApp(
  appDir = file.path(getwd(), "extras", "shiny"),
  appName = appName,
  forceUpdate = TRUE,
  logLevel = "verbose"
)
