# DO NOT EDIT THIS FILE
# IT IS USED IN THE GITHUB ACTION

devtools::load_all()
exportStaticApp(result = omopViewerResults, directory = here::here("extras"))
rsconnect::setAccountInfo(name = "dpa-pde-oxford",
                          token = Sys.getenv("SHINYAPPS_TOKEN"),
                          secret = Sys.getenv("SHINYAPPS_SECRET"))
rsconnect::deployApp(appDir = "extras/shiny", appName = appName, forceUpdate = TRUE)
