name: Generate and Deploy Shiny App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: Run script to generate Shiny app
        run: Rscript extras/createDefaultShiny.R

      - name: Deploy to shinyapps.io
        #if: github.event_name != 'pull_request'
        env:
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          install.packages("rsconnect")
          rsconnect::setAccountInfo(name = "dpa-pde-oxford",
                                    token = Sys.getenv("SHINYAPPS_TOKEN"),
                                    secret = Sys.getenv("SHINYAPPS_SECRET"))
          rsconnect::deployApp(appDir = "extras/shiny", appName = "OmopViewerExample")
