name: Generate results and commit if different

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  update_results:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    concurrency:
      group: pr-${{ github.event.pull_request.number }}
      cancel-in-progress: true

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest, r: '4.3.3'}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Create new results data set
        run: Rscript data-raw/results.R

      - name: Commit if new results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add data/OmopViewerResults.rda

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update OmopViewerResults.rda"
            git push
          fi
